services:
  - type: web
    name: soapp-liste-equipe
    runtime: static
    staticPublishPath: .
    buildCommand: ""
    autoDeploy: true
    # URL définitive après déploiement : https://soapp-liste-equipe.onrender.com
